[dev]
  command = "yarn start" # Command to start your dev server
  port = 3999 # Port that the dev server will be listening on
  publish = "dist" # If you use a _redirect file, provide the path to your static content folder


[build]
  command = "gatsby build"
  publish = "public/"

[template]
  incoming-hooks = ["Ghost"]
