version: 2
jobs:
  lighthouse:
    working_directory: /tmp/build
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - run:
          working_directory: /tmp/build/api
          command: |
            echo "Running lighthouse"
  performance-budget:
    working_directory: /tmp/build
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout

      - run:
          working_directory: /tmp/build
          command: |
            echo "Running Performance Budget"
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - lighthouse
      - performance-budget
